// Country name and code date
import geoData from "./countries-110m-with-country-code.json";

// Grab the array of country geometries
const countryGeoms = geoData.objects.countries.geometries;

/**
 * Build a map from country code → flag emoji.
 * Each geometry’s properties include `{ code: "US", flag: "🇺🇸" }` :contentReference[oaicite:0]{index=0}
 */
const codeToFlag = countryGeoms.reduce((map, geom) => {
  const { code, flag } = geom.properties;
  if (code && flag) map[code] = flag;
  return map;
}, Object.create(null));

/**
 * Get the flag emoji for a given country alpha-2 code.
 * @param {string} code - e.g. "FR", "JP"
 * @returns {string|null} The flag emoji or null if not found.
 */
export function getFlagByCountryCode(code) {
  if (code) {
    return codeToFlag[code.toUpperCase()] || null;
  }
}

export const COUNTRIES = [
  { id: "AF", name: "Afghanistan", continent_code: "AS" },
  { id: "AL", name: "Albania", continent_code: "EU" },
  { id: "DZ", name: "Algeria", continent_code: "AF" },
  { id: "AO", name: "Angola", continent_code: "AF" },
  { id: "AQ", name: "Antarctica", continent_code: "AQ" },
  { id: "AR", name: "Argentina", continent_code: "SA" },
  { id: "AM", name: "Armenia", continent_code: "AS" },
  { id: "AU", name: "Australia", continent_code: "OC" },
  { id: "AT", name: "Austria", continent_code: "EU" },
  { id: "AZ", name: "Azerbaijan", continent_code: "AS" },
  { id: "BS", name: "Bahamas", continent_code: "NA" },
  { id: "BD", name: "Bangladesh", continent_code: "AS" },
  { id: "BY", name: "Belarus", continent_code: "EU" },
  { id: "BE", name: "Belgium", continent_code: "EU" },
  { id: "BZ", name: "Belize", continent_code: "NA" },
  { id: "BJ", name: "Benin", continent_code: "AF" },
  { id: "BT", name: "Bhutan", continent_code: "AS" },
  { id: "BO", name: "Bolivia", continent_code: "SA" },
  { id: "BA", name: "Bosnia and Herz.", continent_code: "EU" },
  { id: "BW", name: "Botswana", continent_code: "AF" },
  { id: "BR", name: "Brazil", continent_code: "SA" },
  { id: "BN", name: "Brunei", continent_code: "AS" },
  { id: "BG", name: "Bulgaria", continent_code: "EU" },
  { id: "BF", name: "Burkina Faso", continent_code: "AF" },
  { id: "BI", name: "Burundi", continent_code: "AF" },
  { id: "KH", name: "Cambodia", continent_code: "AS" },
  { id: "CM", name: "Cameroon", continent_code: "AF" },
  { id: "CA", name: "Canada", continent_code: "NA" },
  { id: "CF", name: "Central African Rep.", continent_code: "AF" },
  { id: "TD", name: "Chad", continent_code: "AF" },
  { id: "CL", name: "Chile", continent_code: "SA" },
  { id: "CN", name: "China", continent_code: "AS" },
  { id: "CO", name: "Colombia", continent_code: "SA" },
  { id: "CG", name: "Congo", continent_code: "AF" },
  { id: "CR", name: "Costa Rica", continent_code: "NA" },
  { id: "HR", name: "Croatia", continent_code: "EU" },
  { id: "CU", name: "Cuba", continent_code: "NA" },
  { id: "CY", name: "Cyprus", continent_code: "EU" },
  { id: "CZ", name: "Czechia", continent_code: "EU" },
  { id: "CI", name: "Côte d'Ivoire", continent_code: "AF" },
  { id: "CD", name: "Dem. Rep. Congo", continent_code: "AF" },
  { id: "DK", name: "Denmark", continent_code: "EU" },
  { id: "DJ", name: "Djibouti", continent_code: "AF" },
  { id: "DO", name: "Dominican Rep.", continent_code: "NA" },
  { id: "EC", name: "Ecuador", continent_code: "SA" },
  { id: "EG", name: "Egypt", continent_code: "AF" },
  { id: "SV", name: "El Salvador", continent_code: "NA" },
  { id: "GQ", name: "Eq. Guinea", continent_code: "AF" },
  { id: "ER", name: "Eritrea", continent_code: "AF" },
  { id: "EE", name: "Estonia", continent_code: "EU" },
  { id: "ET", name: "Ethiopia", continent_code: "AF" },
  { id: "FK", name: "Falkland Is.", continent_code: "SA" },
  { id: "FJ", name: "Fiji", continent_code: "OC" },
  { id: "FI", name: "Finland", continent_code: "EU" },
  { id: "TF", name: "Fr. S. Antarctic Lands", continent_code: "OT" },
  { id: "FR", name: "France", continent_code: "EU" },
  { id: "GA", name: "Gabon", continent_code: "AF" },
  { id: "GM", name: "Gambia", continent_code: "AF" },
  { id: "GE", name: "Georgia", continent_code: "EU" },
  { id: "DE", name: "Germany", continent_code: "EU" },
  { id: "GH", name: "Ghana", continent_code: "AF" },
  { id: "GR", name: "Greece", continent_code: "EU" },
  { id: "GL", name: "Greenland", continent_code: "NA" },
  { id: "GT", name: "Guatemala", continent_code: "NA" },
  { id: "GN", name: "Guinea", continent_code: "AF" },
  { id: "GW", name: "Guinea-Bissau", continent_code: "AF" },
  { id: "GY", name: "Guyana", continent_code: "SA" },
  { id: "HT", name: "Haiti", continent_code: "NA" },
  { id: "HN", name: "Honduras", continent_code: "NA" },
  { id: "HU", name: "Hungary", continent_code: "EU" },
  { id: "IS", name: "Iceland", continent_code: "EU" },
  { id: "IN", name: "India", continent_code: "AS" },
  { id: "ID", name: "Indonesia", continent_code: "AS" },
  { id: "IR", name: "Iran", continent_code: "AS" },
  { id: "IQ", name: "Iraq", continent_code: "AS" },
  { id: "IE", name: "Ireland", continent_code: "EU" },
  { id: "IL", name: "Israel", continent_code: "AS" },
  { id: "IT", name: "Italy", continent_code: "EU" },
  { id: "JM", name: "Jamaica", continent_code: "NA" },
  { id: "JP", name: "Japan", continent_code: "AS" },
  { id: "JO", name: "Jordan", continent_code: "AS" },
  { id: "KZ", name: "Kazakhstan", continent_code: "AS" },
  { id: "KE", name: "Kenya", continent_code: "AF" },
  { id: "KW", name: "Kuwait", continent_code: "AS" },
  { id: "KG", name: "Kyrgyzstan", continent_code: "AS" },
  { id: "LA", name: "Laos", continent_code: "AS" },
  { id: "LV", name: "Latvia", continent_code: "EU" },
  { id: "LB", name: "Lebanon", continent_code: "AS" },
  { id: "LS", name: "Lesotho", continent_code: "AF" },
  { id: "LR", name: "Liberia", continent_code: "AF" },
  { id: "LY", name: "Libya", continent_code: "AF" },
  { id: "LT", name: "Lithuania", continent_code: "EU" },
  { id: "LU", name: "Luxembourg", continent_code: "EU" },
  { id: "MK", name: "Macedonia", continent_code: "EU" },
  { id: "MG", name: "Madagascar", continent_code: "AF" },
  { id: "MW", name: "Malawi", continent_code: "AF" },
  { id: "MY", name: "Malaysia", continent_code: "AS" },
  { id: "ML", name: "Mali", continent_code: "AF" },
  { id: "MR", name: "Mauritania", continent_code: "AF" },
  { id: "MX", name: "Mexico", continent_code: "NA" },
  { id: "MD", name: "Moldova", continent_code: "EU" },
  { id: "MN", name: "Mongolia", continent_code: "AS" },
  { id: "ME", name: "Montenegro", continent_code: "EU" },
  { id: "MA", name: "Morocco", continent_code: "AF" },
  { id: "MZ", name: "Mozambique", continent_code: "AF" },
  { id: "MM", name: "Myanmar", continent_code: "AS" },
  { id: "NA", name: "Namibia", continent_code: "AF" },
  { id: "NP", name: "Nepal", continent_code: "AS" },
  { id: "NL", name: "Netherlands", continent_code: "EU" },
  { id: "NC", name: "New Caledonia", continent_code: "OC" },
  { id: "NZ", name: "New Zealand", continent_code: "OC" },
  { id: "NI", name: "Nicaragua", continent_code: "NA" },
  { id: "NE", name: "Niger", continent_code: "AF" },
  { id: "NG", name: "Nigeria", continent_code: "AF" },
  { id: "KP", name: "North Korea", continent_code: "AS" },
  { id: "NO", name: "Norway", continent_code: "EU" },
  { id: "OM", name: "Oman", continent_code: "AS" },
  { id: "PK", name: "Pakistan", continent_code: "AS" },
  { id: "PS", name: "Palestine", continent_code: "AS" },
  { id: "PA", name: "Panama", continent_code: "NA" },
  { id: "PG", name: "Papua New Guinea", continent_code: "OC" },
  { id: "PY", name: "Paraguay", continent_code: "SA" },
  { id: "PE", name: "Peru", continent_code: "SA" },
  { id: "PH", name: "Philippines", continent_code: "AS" },
  { id: "PL", name: "Poland", continent_code: "EU" },
  { id: "PT", name: "Portugal", continent_code: "EU" },
  { id: "PR", name: "Puerto Rico", continent_code: "NA" },
  { id: "QA", name: "Qatar", continent_code: "AS" },
  { id: "RO", name: "Romania", continent_code: "EU" },
  { id: "RU", name: "Russia", continent_code: "EU" },
  { id: "RW", name: "Rwanda", continent_code: "AF" },
  { id: "SS", name: "S. Sudan", continent_code: "AF" },
  { id: "SA", name: "Saudi Arabia", continent_code: "AS" },
  { id: "SN", name: "Senegal", continent_code: "AF" },
  { id: "RS", name: "Serbia", continent_code: "EU" },
  { id: "SL", name: "Sierra Leone", continent_code: "AF" },
  { id: "SK", name: "Slovakia", continent_code: "EU" },
  { id: "SI", name: "Slovenia", continent_code: "EU" },
  { id: "SB", name: "Solomon Is.", continent_code: "OC" },
  { id: "SO", name: "Somalia", continent_code: "AF" },
  { id: "ZA", name: "South Africa", continent_code: "AF" },
  { id: "KR", name: "South Korea", continent_code: "AS" },
  { id: "ES", name: "Spain", continent_code: "EU" },
  { id: "LK", name: "Sri Lanka", continent_code: "AS" },
  { id: "SD", name: "Sudan", continent_code: "AF" },
  { id: "SR", name: "Suriname", continent_code: "SA" },
  { id: "SE", name: "Sweden", continent_code: "EU" },
  { id: "CH", name: "Switzerland", continent_code: "EU" },
  { id: "SY", name: "Syria", continent_code: "AS" },
  { id: "TW", name: "Taiwan", continent_code: "AS" },
  { id: "TJ", name: "Tajikistan", continent_code: "AS" },
  { id: "TZ", name: "Tanzania", continent_code: "AF" },
  { id: "TH", name: "Thailand", continent_code: "AS" },
  { id: "TL", name: "Timor-Leste", continent_code: "AS" },
  { id: "TG", name: "Togo", continent_code: "AF" },
  { id: "TT", name: "Trinidad and Tobago", continent_code: "NA" },
  { id: "TN", name: "Tunisia", continent_code: "AF" },
  { id: "TR", name: "Turkey", continent_code: "EU" },
  { id: "TM", name: "Turkmenistan", continent_code: "AS" },
  { id: "UG", name: "Uganda", continent_code: "AF" },
  { id: "UA", name: "Ukraine", continent_code: "EU" },
  { id: "AE", name: "United Arab Emirates", continent_code: "AS" },
  { id: "GB", name: "United Kingdom", continent_code: "EU" },
  { id: "US", name: "United States of America", continent_code: "NA" },
  { id: "UY", name: "Uruguay", continent_code: "SA" },
  { id: "UZ", name: "Uzbekistan", continent_code: "AS" },
  { id: "VU", name: "Vanuatu", continent_code: "OC" },
  { id: "VE", name: "Venezuela", continent_code: "SA" },
  { id: "VN", name: "Vietnam", continent_code: "AS" },
  { id: "EH", name: "W. Sahara", continent_code: "AF" },
  { id: "YE", name: "Yemen", continent_code: "AS" },
  { id: "ZM", name: "Zambia", continent_code: "AF" },
  { id: "ZW", name: "Zimbabwe", continent_code: "AF" },
  { id: "SZ", name: "eSwatini", continent_code: "AF" },
] as const;

export type Country = (typeof COUNTRIES)[number];
export type CountryID = (typeof COUNTRIES)[number]["id"];
export type CountryName = (typeof COUNTRIES)[number]["name"];
