// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aakgxyuiobpeuphobmgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFha2d4eXVpb2JwZXVwaG9ibWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTk4NTQsImV4cCI6MjA2OTg5NTg1NH0.p-aJe0w6IYULzVM7ko3YBI9-H1DFODSuvfmsKK1Td74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});